# Generated by Django 4.2.5 on 2023-10-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=5000, verbose_name='Описание'),
        ),
    ]
